package com.example.dcsg1_githubtwogetherapp
val pahangVendors: List<Vendor> = listOf(
    Vendor(
        name = "Hyatt Regency Kuantan Resort",
        category = "Venue",
        rating = 4.7,
        reviewCount = 211,
        priceFrom = "RM61,400",
        imageUrl = null,
        imageResId = R.drawable.hyattregencykuantanresort,
        locationArea = "Kuantan",
        locationState = "Pahang",
        capacity = "200 - 500 pax",
        highlights = "Halal catering, elegant ballroom, resort setting",
        photoResIds = listOf(
            R.drawable.hyattregencykuantanresortview,
            R.drawable.hyattroom,
            R.drawable.hyattlobby,
            R.drawable.hyattballroom,
            R.drawable.hyattrestaurant,
        )
    ),
    Vendor(
        name = "Moments by Cameron Highlands",
        category = "Photographer",
        rating = 4.8,
        reviewCount = 41,
        priceFrom = "RM4,500",
        imageUrl = null,
        imageResId = R.drawable.momentbycameron,
        locationArea = "Cameron Highlands",
        locationState = "Pahang",
        capacity = "Pre-wedding + ROM",
        highlights = "Cinematic editing, drone footage, same-day gallery preview",
        photoResIds = listOf(
            R.drawable.photography10,
            R.drawable.photography11,
            R.drawable.photography12,
        )
    ),
    Vendor(
        name = "Genting Highlands Bridal Makeup",
        category = "Makeup",
        rating = 5.0,
        reviewCount = 121,
        priceFrom = "RM2,000",
        imageUrl = null,
        imageResId = R.drawable.gentinghighlandsbridalmakeup,
        locationArea = "Genting Highlands",
        locationState = "Pahang",
        capacity = "Bridal + family",
        highlights = "Airbrush makeup, hairstyling included, trial session available",
        photoResIds = listOf(
            R.drawable.makeup14,
            R.drawable.makeup15,
            R.drawable.makeup16,
        )
    ),
    Vendor(
        name = "Kuantan Wedding Musicians",
        category = "Live Band",
        rating = 4.4,
        reviewCount = 40,
        priceFrom = "RM5,000",
        imageUrl = null,
        imageResId = R.drawable.kuantanweddingmusicians,
        locationArea = "Kuantan",
        locationState = "Pahang",
        capacity = "Trio band",
        highlights = "Customisable song list, live sound system, formal attire",
        photoResIds = listOf(
            R.drawable.liveband16,
            R.drawable.liveband17,
            R.drawable.liveband18,
        )
    ),
    Vendor(
        name = "MC Cameron Highlands",
        category = "Emcee",
        rating = 4.4,
        reviewCount = 99,
        priceFrom = "RM1,100",
        imageUrl = null,
        imageResId = R.drawable.mccameronhighlands,
        locationArea = "Cameron Highlands",
        locationState = "Pahang",
        capacity = "Trilingual hosting",
        highlights = "Trilingual hosting, custom script, rehearsal included",
        photoResIds = listOf(
            R.drawable.emcee10,
            R.drawable.emcee11,
            R.drawable.emcee12,
        )
    ),
    Vendor(
        name = "Genting Highlands Couture House",
        category = "Attire",
        rating = 4.5,
        reviewCount = 198,
        priceFrom = "RM1,700",
        imageUrl = null,
        imageResId = R.drawable.gentinghighlandscouturehouse,
        locationArea = "Genting Highlands",
        locationState = "Pahang",
        capacity = "2 outfit rentals",
        highlights = "Custom tailoring, fitting sessions included, accessories rental",
        photoResIds = listOf(
            R.drawable.attire_13,
            R.drawable.attire_14,
            R.drawable.attire_15,
        )
    ),
    Vendor(
        name = "Kuantan Event Styling",
        category = "Deco",
        rating = 4.4,
        reviewCount = 161,
        priceFrom = "RM9,900",
        imageUrl = null,
        imageResId = R.drawable.kuantaneventstyling,
        locationArea = "Kuantan",
        locationState = "Pahang",
        capacity = "Up to 100 pax venue",
        highlights = "Floral arch specialist, backdrop customization, setup & teardown included",
        photoResIds = listOf(
            R.drawable.deco_12,
            R.drawable.deco_13,
            R.drawable.deco_14,
            R.drawable.deco_15,
        )
    ),
    Vendor(
        name = "Cameron Highlands Resort",
        category = "Venue",
        rating = 4.7,
        reviewCount = 175,
        priceFrom = "RM51,200",
        imageUrl = null,
        imageResId = R.drawable.cameronhighlandsresort,
        locationArea = "Cameron Highlands",
        locationState = "Pahang",
        capacity = "100 - 300 pax",
        highlights = "Highland resort views, garden ceremony, in-house catering",
        photoResIds = listOf(
            R.drawable.cameronhighlandlobby,
            R.drawable.cameronhighlandroom,
            R.drawable.cameronhighlanddining,
            R.drawable.cameronhighlandwedding,
        )
    )
)