package com.example.dcsg1_githubtwogetherapp

import io.github.jan.supabase.postgrest.from
import kotlinx.serialization.Serializable

/**
 * These two data classes follow the same split as User/UserInput in Practical 9:
 * - SupabaseReview: the shape read from the database, includes id (auto-generated by the DB)
 * - SupabaseReviewInput: the shape used when writing a new review, no id
 *
 * We don't reuse the Review data class from ReviewData.kt directly because Review is meant
 * for the UI (fields like reviewerName use camelCase), while these field names need to
 * match the Supabase table's column names (vendorname/reviewername, all lowercase).
 * A couple of small conversion functions bridge the two.
 */
@Serializable
data class SupabaseReview(
    val id: Int,
    val vendorname: String,
    val reviewername: String,
    val rating: Int,
    val comment: String
)

@Serializable
data class SupabaseReviewInput(
    val vendorname: String,
    val reviewername: String,
    val rating: Int,
    val comment: String
)

private fun SupabaseReview.toReview(): Review = Review(
    id = id,
    reviewerName = reviewername,
    rating = rating,
    comment = comment
)

/**
 * Same structure as fetchUsers() in Practical 9, just with an added filter { eq(...) }
 * to only get reviews for this vendor, not every review.
 * The caller wraps this in withContext(Dispatchers.IO) itself - not done here.
 */
suspend fun fetchReviews(vendorName: String): List<Review> {
    return supabase
        .from("reviews")
        .select {
            filter {
                eq("vendorname", vendorName)
            }
        }
        .decodeList<SupabaseReview>()
        .map { it.toReview() }
}

/**
 * Same structure as addUser() in Practical 9: after inserting, select() pulls back
 * the database-generated id, so the new review has the correct id without us
 * having to guess a nextId ourselves.
 */
suspend fun insertReview(
    vendorName: String,
    reviewerName: String,
    rating: Int,
    comment: String
): Review {
    val inserted = supabase
        .from("reviews")
        .insert(
            SupabaseReviewInput(
                vendorname = vendorName,
                reviewername = reviewerName,
                rating = rating,
                comment = comment
            )
        ) {
            select()
        }
        .decodeSingle<SupabaseReview>()

    return inserted.toReview()
}